services:

  mysql-pedidos:
    image: 'mysql'
    environment:
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=alurafood-pedidos
      - TZ=America/Sao_Paulo
    volumes:
      - /opt/mysql/pedidos:/opt/lib/mysql
      - /opt/mysql/pedidos/*.sql:/docker-entrypoint-initdb.d/*.sql
    ports:
      - '3306:3306'
    networks:
      - alura-food-network

  mysql-pagamentos:
    image: 'mysql'
    environment:
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=alurafood-pagamento
      - TZ=America/Sao_Paulo
    volumes:
      - /opt/mysql/pagamentos:/opt/lib/mysql
      - /opt/mysql/pagamentos/*.sql:/docker-entrypoint-initdb.d/*.sql
    ports:
      - '3307:3307'
    networks:
      - alura-food-network

  server:
    restart: on-failure
    image: 'alexandreluchetti/alura-food/server:1.0.0'
    ports:
      - '8081:8081'
    volumes:
      - /opt/alura-food/server:/opt/lib/alura-food/server
    environment:
      - TZ=America/Sao_Paulo
    networks:
      - alura-food-network

  gateway:
    restart: on-failure
    depends_on:
      - server
    image: 'alexandreluchetti/alura-food/gateway:1.0.0'
    ports:
      - '8082:8082'
    volumes:
      - /opt/alura-food/gateway:/opt/lib/alura-food/gateway
    environment:
      - TZ=America/Sao_Paulo
    networks:
      - alura-food-network

  pedidos:
    restart: on-failure
    depends_on:
      - mysql-pedidos
      - server
      - gateway
    image: 'alexandreluchetti/alura-food/pedidos:1.0.0'
    ports:
      - '8083:8083'
    volumes:
      - /opt/alura-food/pedidos:/opt/lib/alura-food/pedidos
    environment:
      - TZ=America/Sao_Paulo
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-pedidos:3306/alurafood-pedidos
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - alura-food-network

  pagamentos:
    restart: on-failure
    depends_on:
      - mysql-pedidos
      - mysql-pagamentos
      - server
      - gateway
    image: 'alexandreluchetti/alura-food/pagamentos:1.0.0'
    ports:
      - '8084:8084'
    volumes:
      - /opt/alura-food/pagamentos:/opt/lib/alura-food/pagamentos
    environment:
      - TZ=America/Sao_Paulo
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-pagamentos:3306/alurafood-pagamento
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - alura-food-network

networks:
  alura-food-network:
    driver: bridge
  java-network:
    external: true